### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 110

### ISSUE THREAD

**Issue by hildebrau** [altodd/Southwest-Docker#6]
I just tried pulling the latest image and running it interactively to see the stdout and it shows this:

$ docker run -it altodd/southwest-docker schedule xxxxxx xxxx xxxxxx xxx@xxx.com
Starting deferred execution scheduler: atd.
Starting periodic command scheduler: cron.
Traceback (most recent call last):
  File "/headers/southwest-headers/southwest-headers.py", line 22, in <module>
    driver = uc.Chrome(headless = True)
  File "/headers/southwest-headers/env/lib/python3.9/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/headers/southwest-headers/env/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 429, in __init__
    super(Chrome, self).__init__(
  File "/headers/southwest-headers/env/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/headers/southwest-headers/env/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 106, in __init__
    super().__init__(
  File "/headers/southwest-headers/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/headers/southwest-headers/env/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 715, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/headers/southwest-headers/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/headers/southwest-headers/env/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/headers/southwest-headers/env/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
**selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:35490
from session not created: This version of ChromeDriver only supports Chrome version 110
Current browser version is 108.0.5359.124**
Stacktrace:
#0 0x55b7dcda7d93 <unknown>
#1 0x55b7dcb762d7 <unknown>
#2 0x55b7dcba32f4 <unknown>
#3 0x55b7dcb9a2fc <unknown>
#4 0x55b7dcbdf4f4 <unknown>
#5 0x55b7dcbd6353 <unknown>
#6 0x55b7dcba5e40 <unknown>
#7 0x55b7dcba7038 <unknown>
#8 0x55b7dcdfb8be <unknown>
#9 0x55b7dcdff8f0 <unknown>
#10 0x55b7dcddff90 <unknown>
#11 0x55b7dce00b7d <unknown>
#12 0x55b7dcdd1578 <unknown>
#13 0x55b7dce25348 <unknown>
#14 0x55b7dce254d6 <unknown>
#15 0x55b7dce3f341 <unknown>
#16 0x7f7bd78f5ea7 start_thread

**Comment by hildebrau** [comment]
I guess this probably has something to do with https://github.com/byalextran/southwest-headers/issues/6; but my brain is exhausted and I'm not sure where to go from here.. SWA check in in the morning. ;(

**Comment by altodd** [comment]
Hey, sorry! I just had the same issue when I tried to schedule check in. I must have missed the e-mail for this. I just rebuilt and didn't have that error after a new build. I pushed the new image.

**Comment by altodd** [comment]
Actually, I closed this too hastily, after the container runs a minute the rebuild doesn't do anything. Thanks for the point to the issue on southwest-headers as that is the problem. I'll get this updated.

**Comment by altodd** [comment]
Okay, latest commit actually works. Updated to install version 109 of chrome and am pushing the updated image now. Also set up image to run with user of non root before realizing that didn't solve the issue but am keeping that as it doesn't hurt to have a non-root user.
