### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by bhahn1800** [altodd/Southwest-Docker#9]
I just ran today and am getting the following.  Let me know if there is a workaround

`docker pull altodd/southwest-docker`

`docker run altodd/southwest-docker schedule Confirmation First Last`

```
Starting deferred execution scheduler: atd.
Starting periodic command scheduler: cron.
/var/lib/gems/2.7.0/gems/autoluv-0.3.2/lib/autoluv.rb:33:in `log': undefined method `+' for nil:NilClass (NoMethodError)
        from /var/lib/gems/2.7.0/gems/autoluv-0.3.2/lib/autoluv.rb:46:in `notify_user'
        from /var/lib/gems/2.7.0/gems/autoluv-0.3.2/bin/autoluv:26:in `rescue in <top (required)>'
        from /var/lib/gems/2.7.0/gems/autoluv-0.3.2/bin/autoluv:12:in `<top (required)>'
        from /usr/local/bin/autoluv:23:in `load'
        from /usr/local/bin/autoluv:23:in `<main>'
/var/lib/gems/2.7.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response': 403 Forbidden (RestClient::Forbidden)
        from /var/lib/gems/2.7.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
        from /var/lib/gems/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
        from /var/lib/gems/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
        from /usr/lib/ruby/2.7.0/net/http.rb:933:in `start'
        from /var/lib/gems/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
        from /var/lib/gems/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
        from /var/lib/gems/2.7.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
        from /var/lib/gems/2.7.0/gems/rest-client-2.1.0/lib/restclient.rb:66:in `get'
        from /var/lib/gems/2.7.0/gems/autoluv-0.3.2/lib/autoluv/southwestclient.rb:91:in `departing_flights'
        from /var/lib/gems/2.7.0/gems/autoluv-0.3.2/lib/autoluv/southwestclient.rb:22:in `schedule'
        from /var/lib/gems/2.7.0/gems/autoluv-0.3.2/bin/autoluv:19:in `<top (required)>'
        from /usr/local/bin/autoluv:23:in `load'
        from /usr/local/bin/autoluv:23:in `<main>'
```

**Comment by altodd** [comment]
This seems to be an issue possibly with chrome driver in the upstream repo (see byalextran/southwest-checkin#18). I will try and watch that and update if possible. Looks like https://github.com/jdholtz/auto-southwest-check-in/ may work. I haven't had a flight recently so I can't say for sure.
